[project]
name = "openems-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.10.5",
    "h5py>=3.13.0",
    "ipykernel>=6.29.5",
    "jax[cuda12]>=0.5.3",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "ruff>=0.9.5",
    "scipy>=1.15.1",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "typer-slim>=0.15.2",
]

[tool.ruff.lint]
select = [
    # isort
    "I",
    # pyflakes
    "F",
]
exclude = ["src/*"] # these scripts run inside OpenEMS container
